### ISSUE TITLE
Hydraulic failure mortality of high latitude vegetation

### ISSUE THREAD

**Issue by JessicaNeedham** [NGEET/fates#1105]
I was plotting mortality mechanisms by PFT for a global no comp run and found high hydraulic  failure mortality of broadleaf cold deciduous extra tropical shrubs and arctic C3 grasses, despite fates_mort_hf_sm_threshold still being very low as identified in #1085. It looks like freezing is causing soil moisture to get very low, which is triggering this mortality mechanism. Note that hydro is off in this run. This is probably not a response that we want.

![Screenshot 2023-10-25 at 12 51 16](https://github.com/NGEET/fates/assets/10586303/08f1d79d-7ebf-429b-8efe-465954ce2059)

**Comment by rosiealice** [comment]
This low swp in frozen soils was a bit issue with Marius's work with FATES HYDRO in cold regions. In that case, we had to make hardened plants hugely reduce their conductance to prevent desiccation. 

I guess in non hydro mode we could disallow hydraulic mortality if the soil temperature is low?

**Comment by ckoven** [comment]
Thanks @JessicaNeedham for spotting this, and agreed that we should probably ignore hydraulic mortality if soils are frozen. Since FATES [has access to soil temperature profiles](https://github.com/NGEET/fates/blob/main/main/FatesInterfaceTypesMod.F90#L461), it should be easy to implement.

Two further questions though: 

1. Do we pick some specific depth (10cm?) and turn off hydraulic mortality if that specific soil layer is frozen, or do we turn off hydraulic mortality if any soil layer is frozen? Pros/cons of each would seem to be that if we pick a certain depth, then we are basically picking a discrete lag time with respect to air temperature, and so things may behave weirdly in one or the other shoulder season; whereas if we do it for all soil layers, then it will always be off throughout the year for the entire permafrost region (which may be what we want).

2. Do we also need to put in logic for btran calculation itself or just the effect of btran on mortality?  I vaguely remember going down a rabbit hole on this point of what the effect of frozen soils should be on btran with @zmsubin, @jinyun1tang and others >10 years ago in CLM code (and inherited mostly unchanged it seems by ELM). Looking at the current big-leaf code, it seems like the logic is turned off to ignore frozen layers (or permafrost layers only) via the two hard-coded switches at the top of the modules (`perchroot` and `perchroot_alt`), but in layers where temperature is less than some threshold (-2ºC for CLM, some named parameter in ELM) the root resistance term in the btran calculation is set to zero which I think might have the equivalent effect?

    see:
    https://github.com/ESCOMP/CTSM/blob/master/src/biogeophys/SoilMoistStressMod.F90#L384-L386

    https://github.com/E3SM-Project/E3SM/blob/master/components/elm/src/biogeophys/SoilMoistStressMod.F90#L371-L372

**Comment by JessicaNeedham** [comment]
@ckoven  it looks like FATES only calculates btran for [liquid soil water layers](https://github.com/NGEET/fates/blob/1d18bb69ee47a14467c172879ea0083dc8178012/biogeophys/EDBtranMod.F90#L158), based on the[ -2 threshold](https://github.com/NGEET/fates/blob/1d18bb69ee47a14467c172879ea0083dc8178012/biogeophys/EDBtranMod.F90#L51). If soils are freezing then btran remains zero, which is triggering the hydraulic failure mortality. To your second question, are you suggesting that btran maybe shouldn't be zero if soils are frozen? 

As a simple fix I’ve changed the calculation of hmort to only occur when all soil layers are above -2 degrees C ([here](https://github.com/NGEET/fates/commit/90f50ba399e8a7998874b74f0cae81b8dd13c2aa)). I’m running a short test now but I want to hold off on a longer test to hear what people think of this solution. It seems confusing to check for soil temperature twice.

**Comment by rosiealice** [comment]
I think this is fine Jessie. It means we won't get HF for complex frost drought /winter warming type events, but these should probably at any rate be linked at a minimum to a model of hardening per Marius' work, so I think in the absence of that it is fine to disallow HF for cold soils.

**Comment by glemieux** [comment]
Closing per #1115
