### ISSUE TITLE
Carbon budget reporting not closed in API 32 onwards

### ISSUE THREAD

**Issue by JessicaNeedham** [NGEET/fates#1203]
The cumulative sum of (allocation + new recruits) -  ( mortality +  turnover ) should equal  vegetation carbon. This was true in previous tags, but from API 32 onwards this is no longer true if disturb_frac > 0. I’m guessing that impact mortality is not being tracked properly or there is a problem tracking new patches somewhere. 

![Screenshot 2024-05-17 at 21 22 49](https://github.com/NGEET/fates/assets/10586303/43feb3d3-0c3b-43ae-83e1-b443091db5ac)

![Screenshot 2024-05-17 at 21 23 25](https://github.com/NGEET/fates/assets/10586303/abc899b0-93e4-4ef5-a006-c14e03a6a1ff)

![Screenshot 2024-05-17 at 21 38 23](https://github.com/NGEET/fates/assets/10586303/8f90ec6b-ad33-4e3d-be3e-71714dbf65ff)

Jupyter notebook here: https://github.com/JessicaNeedham/FATES-plotting-scripts/blob/main/API33_disturb_frac.ipynb
I cherry picked recruit carbon flux since that came in with PR  #1153 post API 32 but is necessary for looking at the carbon budget in this way.

**Comment by XiulinGao** [comment]
I was looking at the code recently and noticed that this line of code was removed for fire disturbance in EDPatchdynamics for API32 
! loss of individuals from source patch due to area shrinking
 currentCohort%n = currentCohort%n * (1._r8 - patch_site_areadis/currentPatch%area)

Do you think this might be the reason why we see the mismatch between carbon budgets?

**Comment by JessicaNeedham** [comment]
Fire is off in these test simulations so I don't think it is causing the issues I'm seeing.

**Comment by JessicaNeedham** [comment]
This seems to be resolved as of API35.
