### ISSUE TITLE
Adding new Arctic shrub PFTs

### ISSUE THREAD

**Issue by jenniferholm** [NGEET/fates#1204]
Hi all,  I'd like to increase our number of shrub PFTs to allow for PFTs that have traits specific to arctic environments. But wanted to first raise the discussion here, and see if people also agree with this.   

For now, I'd only like to copy the broadleaf_evergreen_extratrop_shrub and the broadleaf_colddecid_extratrop_shrub and make two new PFTs that can contain parameter traits based on observations and sensitivity analysis in the Arctic.  Potentially named: "broadleaf_evergreen_arctic_shrub" and "broadleaf_colddecid_arctic_shrub".  This is so that more temperate and boreal shrubs can still compete with arctic shrubs, and to distinguish the traits/characteristics between the arctic environments that are pretty distinct. The initial parameterization updates will come from Yanlan Liu's 2024 FATES paper that is under review.   (This is also needed for NGEE Arctic specific simulations). 
To do this update, I'll also need to update the fates_hlm_pft_map, and add 2 more FATES columns. Simultaneously (at least in ELM for now) we will also be adding in two new arctic PFTs on the ELM side based on Sulman et al. 2021

https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2020MS002396

For context, we've had lots of discussions in the past about how to handle PFTs.  Before FATES had a longer list of biome specific PFTs (i.e., tropical, temperate, boreal like in CLM/ELM), but then condensed them to tropical and extratropical distinction only. This was important so that we didn't have bioclimatic envelopes already predetermining the PFTs, and we could use the FATES trait filtering and mechanistic competition to determine PFT distributions.  
However, if we update the traits for only the current broadleaf_evergreen_extratrop_shrub with _only_ traits from Arctic observations, they won't really make sense for evergreen shrubs located at much lower latitudes.  So we need to include for different set of traits that allow for multiple shrub types to exist and compete. 

What do people think?

**Comment by wwieder** [comment]
I'm supportive of this, @jenniferholm thanks for bringing up the topic.  Out of curiosity, what are examples evergreen arctic shrubs?  Is this some kind of low stature 'cushion plants'?  We have lots of these in the alpine, and I'm assuming there are common in arctic ecosystems too?

FWIW, I think for CLM we'd only be able to map the FATES PFT to a single arctic shrub PFT with the information we currently have on our surface datasets, but maybe could add this for regional or single point surface data?

**Comment by glemieux** [comment]
Just a quick note that this conversation spurred me to generate a fates user's guide page dedicated to capturing the default map and provide references for it: https://fates-users-guide.readthedocs.io/en/latest/user/HLM-FATES-PFT-map.html

Please feel free to add to it as necessary.

**Comment by ckoven** [comment]
Thanks @jenniferholm for starting this! One comment is that I don't think we want to use HLM PFT#9 for this purpose though (or really much of anything), because it is barely present, has gotten less present over various iterations of the surface datasets, and isn't present in the Arctic at all.  I was curious so I made [a notebook with PFT distributions from a few different surface files](https://github.com/ckoven/hlm_pft_maps/blob/main/surfdata_pft_map_plots.ipynb), and specifically used a colormap that starts at 1 percent to show PFTs that are even just barely present. The HLM PFT 9 barely shows up at all, and mainly a bit around the mediterranean and in East Africa. In the older, 2013 file, it is more present, in the 2017 files it is barely there at all. 

So I'd suggest instead,. at least for the purposes of the HLM:FATES PFT mapping, just splitting off the HLM PFT number 11 into two new FATES PFTs instead, using something like the 10%/90% partitioning that you mentioned.

**Comment by jenniferholm** [comment]
Hi @ckoven - great, thanks for the suggestion and also providing the PFT distribution mapping from the surface files!  
Your recommendation definitely makes sense to me, and I think is the way to go.   

I'll proceed with splitting the HLM PFT number 11 into two new FATES PFTs, and use the 10%/90% partitioning.  For the "non-arctic" 10% cold-deciduous shrub PFT, I guess I might as well go ahead and update those PFT parameters with the values from my boreal forest sensitivity and calibration testing.  If there are no objections? (This work is not published yet, but these are parameter values that I've passed over to other folks for various boreal forest and global testing....)

**Comment by jenniferholm** [comment]
Hi all, in addition to making a new cold-deciduous arctic shrub PFT, I'll also be updating about 20 of the default parameters for the current c3 arctic grass PFT.   
But I wanted to double check with @XiulinGao about the grass allometry work you are doing.  In your PR #1206 I noticed you updated the allometry parameters for all 3 grasses, and also added in code changes for [grass specific agw, sap, leaf allometry](https://github.com/NGEET/fates/pull/1206/commits/b2e4194d26c68b918506240182749aa8a275d9a7).  So I'm wondering.... do you think we should stick to your allometry parameter updates, even for the c3_arctic_grass PFT, or is it okay if I update the parameters to the arctic values we found that worked in the Alaska? I'm also asking because I can't fully remember if you updated the allometric functions themselves (and which ones?) and if we need to use certain parameters that go with these new grass functional forms.   I hope this all makes sense. 

For reference, the allometry parameters I would update for the c3 arctic grass are:
fates_allom_d2bl1
fates_allom_d2bl2
fates_allom_agb2
fates_allom_agb3
fates_allom_d2h1
fates_allom_d2h2
fates_allom_dbh_maxheight

**Comment by rosiealice** [comment]
Have you tested the GPP of the arctic grass in SP mode (or otherwise)? I am seeing quite high biases in the arctic c3 grass regions. Wondering if any of these parameter updates might address them?

**Comment by jenniferholm** [comment]
Hi Rosie, good question. No I haven't done any SP mode tests, but I can do that once the new arctic c3 grass parameters are in.  
I'm guessing that either Xiulin's grass allometry PR will improve things for Mediterranean-climate grasses, or these c3 arctic grass parameter updates will hopefully improve things for constraining to more high latitudes.  But not fully sure.

**Comment by alistairrogers** [comment]
Hi All,
In 2023 we made a bunch of measurements to cover gaps in the physiological characterization of Arctic PFTs this includes deciduous shrubs, but also the evergreen shrubs (low stature, gnarly). We also have lots of data on the grasses. Some of this is published already but more is emerging. In short, there's a much richer data set than the one in Yanlan's paper. FYI Verity Salmon and I will be leading an effort in NGEE Arctic to synthesize all the Arctic plant trait data to inform parameterization efforts for the NGEE Arctic model. Note that Arctic shrub allometry is a thorny issue, Verity and Daryl Yang (NGEE Arctic - ORNL) would be good POCs on this.

Rosie,
High GPP in the Arctic may be due to model assumptions for quantum yield. In CLM4.5 QY is high anyway (essentially the theoretical maximum of dark-adapted unstressed plants) and low-temperature sensitivity of QY would exacerbate this ([Rogers et al 2019](https://nph.onlinelibrary.wiley.com/doi/full/10.1111/nph.15750)). See f in Table 1 and Figure 4. I believe FATES also uses the same high QY (f=0.15). I'm involved in a paper with Xueli Huo et al. that included the finding that reducing QY resulted in a better model match with ILAMB benchmarks for the Arctic and Boreal Region (in revision JGR Biogeosciences) further suggesting that tweaking QY might make sense.

**Comment by rosiealice** [comment]
Hey thanks @alistairrogers! Will try that for sure. What's a sensible lower bound on the QY? 

Nothing also that Vigdis Vandvik's group in Bergen are planning to synthesise their shrub trait data to help inform FATES, so it would be cool to join forces and make a really good set of constraints. They were advertising for a postdoc, I'll check in to see how it's going.

**Comment by alistairrogers** [comment]
You should be able to calculate a lower bound from my 2019 paper (look at the 5oC mean in figure 4) but happy to do that for you if that's helpful. What is your model input? Suspecting f, unfortunately, the QY yield literature has several ways of reporting values so let me know what parameter and units you need,  Good to hear about Vigis Vandvik's effort, thanks for sharing.

**Comment by XiulinGao** [comment]
> Hi all, in addition to making a new cold-deciduous arctic shrub PFT, I'll also be updating about 20 of the default parameters for the current c3 arctic grass PFT. But I wanted to double check with @XiulinGao about the grass allometry work you are doing. In your PR #1206 I noticed you updated the allometry parameters for all 3 grasses, and also added in code changes for [grass specific agw, sap, leaf allometry](https://github.com/NGEET/fates/pull/1206/commits/b2e4194d26c68b918506240182749aa8a275d9a7). So I'm wondering.... do you think we should stick to your allometry parameter updates, even for the c3_arctic_grass PFT, or is it okay if I update the parameters to the arctic values we found that worked in the Alaska? I'm also asking because I can't fully remember if you updated the allometric functions themselves (and which ones?) and if we need to use certain parameters that go with these new grass functional forms. I hope this all makes sense.
> 
> For reference, the allometry parameters I would update for the c3 arctic grass are: fates_allom_d2bl1 fates_allom_d2bl2 fates_allom_agb2 fates_allom_agb3 fates_allom_d2h1 fates_allom_d2h2 fates_allom_dbh_maxheight

Hi Jennifer,

I am not sure if the new grass allometry will improve your arctic simulations including a arctic C3 grass. I guess a simple solution is to do two test runs using the two different allometry settings and try to see which performs better in your case. I decided to update all the grass allometry parameters is because those default parameters are not based on grass-specific data and we now have empirically-derived parameters so thought it would make more sense to use those. I did included a grass-specific AGB, leaf, and sapwood allometry function but you can always switch back to the original allometry model and use your own parameters if these are based on observations from your study region. Yes, the data for developing those new grass allometry are all from Mediterranean grasses.

**Comment by jenniferholm** [comment]
Hi all,  Great, thanks for this feedback!  

@alistairrogers - good to know there is a much richer data set coming, especially for grasses and for shrub allometry! And we'll definitely be in touch with Verity about her NGEE Arctic work to synthesize all the Arctic plant trait data to inform parameterization efforts. We've already had some conversations with her, and will keep checking on the new trait data. 

To stick with our timelines, I think it's best to add in Yanlan's current shrub parameter traits as a first pass.  And we can continually update the parameter values as the new data is tested, improved, and synthesized.  The work here will also add in a whole new arctic deciduous shrub PFT, which will be a good first step.  Then that new arctic shrub (and existing c3 arctic grass) can continually get refined with better traits.  
Let's definitely touch base with Verity soon! 

@XiulinGao - Thanks for your insights.  In our work we still used the original allometry functions and modes and only updated the coefficients from our sensitivity analysis.  It's great that you have functional forms that are more grass specific, and grass specific data.  So I think the best plan is to stick with your PR https://github.com/NGEET/fates/pull/1206 (which has the improvements of grass specific allometry), for now, and then we can make updates later.
