### ISSUE TITLE
patch and cohort initialization needs love

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#231]
The current method of creating new patches and cohorts seems to be to something close to the following:
1) allocate memory structure
2) assign linked list pointers
3) initialization many variables with zeros.

I'm not to thrilled with part 3.  I would rather us initialize everything with a NaN following the mold of CLM/ALM, and use the CIME library definition of nan.   

Then we can have a section where we target specific variables that should be zero'd (or other constants), and give the scientifically justifiable reason for it in each case.  I really don't want to zero a variable that is intended to be over-written later, only for it to slip through the cracks, not receive the correct initialization, and that zero to allow the model to keep plugging along and use that bogus value.

Of course, some initial conditions are passed in as arguments, and should remain that way.

**Comment by jkshuman** [comment]
Revisiting this issue as @rgknox and I have had some discussion about cleaning up the extensive NaN followed by zeroing of variables (for instance in EDCohortDynamics: https://github.com/NGEET/fates/blob/3f6749d471e8766a212dd0a2b0c4c95aacd97f65/biogeochem/EDCohortDynamicsMod.F90#L436  and then
https://github.com/NGEET/fates/blob/3f6749d471e8766a212dd0a2b0c4c95aacd97f65/biogeochem/EDCohortDynamicsMod.F90#L546 ) has many of the same variables.

on the question of NaN and zeroing of variables @rgknox recommended this:
"I recommend NAN'ing everything whenever a new variable is created, so include these along with the other cohort variables that get NAN'd.

Regarding zero'ing.  I think we should only be zero'ing a variable when there is a meaningful intention behind it.  If a variable is going to be incremented over a loop, then I would zero it right before the loop, and only the indices in the loop.  If a variable is going to be incremented over a few subroutines, then maybe create a very visible subroutine to zero the variable before those subroutines, and group it with others doing the same thing.  But, if a variable is not incremented, I would avoid zero'ing, because this will make it hard to determine later in the code, if the variable is used, if a value of zero means its really zero, or was just ignored or missed."

**Comment by rosiealice** [comment]
I agree, I'm not attached to the zeroing situation... Going with NaNs seems like a more robust way to catch errors...

**Comment by rgknox** [comment]
We have reoriented how we newly define cohort variables in recent times, following these ideas.  I don't see a massive refactor on how we create cohorts coming anytime soon though.  Lets close and re-evaluated someday if need be.
