### ISSUE TITLE
The quadratic calculation of stomatal conductance in FATES

### ISSUE THREAD

**Issue by youwasha** [NGEET/fates#446]
Hi all, 

I'm a new one for the FATES model,  I'm learning the FATES code right now. In FATES PlantRespPhotosynthMod, I only found an quadratic calculation to get stomatal conductance (gs) at each leaf layer (line 990-1000), Ball-Berry equation is just used as a comparison (line 1060-1067).  I feel a little confused about why they use this quadratic equation.

I'll appreciate if someone can explain more about this. Thanks!

**Comment by dlebauer** [comment]
for reference these are the lines in question ... https://github.com/NGEET/fates/blob/master/biogeophys/FatesPlantRespPhotosynthMod.F90#L1060

I am just learning about FATES/CLM but I suspect it has to do with the fact that CLM5.0 is using the [MEDLYN et al 2011](https://github.com/NGEET/fates/files/2630981/MEDLYN_et_al-2011-Global_Change_Biology.pdf)model of stomatal conductance instead of the Ball Berry model that was used through CLM 4.5 (see [CLM 5.0 documentation](https://escomp.github.io/ctsm-docs/doc/build/html/tech_note/Photosynthesis/CLM50_Tech_Note_Photosynthesis.html#photosynthesis). Medlyn et al add a 1/sqrt(D) parameter (eq 1 in the documentation) that was not present in Ball Berry model; without going through the code it isn't clear if this is related...

**Comment by dlebauer** [comment]
Now I see that the code in [line 1067](https://github.com/NGEET/fates/blob/master/biogeophys/FatesPlantRespPhotosynthMod.F90#L1067), `quadratic_f (aquad, bquad, cquad, r1, r2)` is explained in eq 24 of the [CLM 5.0 documentation](https://escomp.github.io/ctsm-docs/doc/build/html/tech_note/Photosynthesis/CLM50_Tech_Note_Photosynthesis.html#equation-9.36) under 'numerical implementation'. 

Kudos to the team for clearly documenting the implementation!

**Comment by rosiealice** [comment]
Indeed, the quadratic terms etc. pre-date the implementation of the Medlyn 2011 model in CLM5. It's worth noting that the FATES numerical implementation of photosynthesis dates from a little prior to the CLM4.5 release, and so is not all the same as the CLM5 technical documentation. There's some discussion by @walkeranthonyp on #443 about this too.  

Note that FATES is still using Ball-Berry, rather than Medlyn, but it's not super difficult to implement Medlyn, if anyone wanted to do that. It only took a couple of lines and a couple of new parameters, and we already have the code from CLM5...

**Comment by youwasha** [comment]
Thanks! @dlebauer @rosiealice , your comments are very helpful! Actually I'm trying to implement Medlyn equation into FATES. Thank you very much!

**Comment by rosiealice** [comment]
Great! That would be a popular development I'm sure. Let us know if you need any more help navigating the terms. In CLM5 we were able to just change the basic gs calculation without modifying the operation of the solver. If you get the point of having some test code, then feel free to point us at it so we can collectively determine whether the CLM5 and FATES solutions differ in any 'interesting' ways. This part of the code can be quite opaque :/

**Comment by walkeranthonyp** [comment]
@youwasha it's a quadratic solve because the gs function is combined with the ficks law equation to get ci from cb, gs, and anet. You need to combine medlyn with ficks law to get the appropriate quadratic and then replace the ball berry derived quadratic parameters (i.e. a b c) with the medlyn derived parameters.

**Comment by youwasha** [comment]
@walkeranthonyp Thank you so much, I'm doing just like what you said ;)
@rosiealice Thanks, I'll make a timely response if I meet some problems. I appreciate your kind help!

**Comment by serbinsh** [comment]
@youwasha I havent seen any updates on this since Dec 2014 but wanted to let you know there is a PR for adding Medlyn led by @Qianyuxuan now for FATES.  It should be an option in the near future.  Here is the PR: https://github.com/NGEET/fates/pull/608

**Comment by rgknox** [comment]
closing as it seems the original question was answered, feel free to comment and re-open if more discussion necessary

**Comment by youwasha** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi Ryan,Hope you are going well. Thanks for letting me know. Hope to meet with you again in the future!Best Wishes,Yan
    
        
            
        
    
    
          
        
            
    
        font{
            line-height: 1.6;
        }
    
Yan Bai, Ph.D Young Research Fellow  College of Atmospheric Sciences, Lanzhou UniversityLanzhou, China, 730000Email: yanbai@lzu.edu.cn

        
    
     
    

    On 08/17/2020 23:29，Ryan Knox<notifications@github.com> wrote： 



closing as it seems the original question was answered, feel free to comment and re-open if more discussion necessary
