### ISSUE TITLE
Benchmarking phenological status

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#465]
I'm adding site level phenological status to the history diagnostics.  This status is for both cold deciduous and drought deciduous.  A status of 1 indicates that the site is either too cold or too dry for vegetation and plants directed towards a "leaf-off" state.  A status of 2 is the opposite, either warm enough or wet-enough for the plants to be directed towards a "leaf-on" state.

Question: Are there any good datasets, preferably global, that we can benchmark these two status flags against?   This seems like something MODIS/landsat would be able to provide...

**Comment by rgknox** [comment]
tagging @jenniferholm , @climate-dude

**Comment by rgknox** [comment]
this product looks useful:
https://lpdaac.usgs.gov/dataset_discovery/measures/measures_products_table/vipphen_evi2_v004

**Comment by mdietze** [comment]
If you’re willing to entertain site-scale data, then go with the Phenocam data — much better than MODIS, which is temporally coarser and a bit biased. That said, in the fall phenocam and MODIS also give different answers because they measure different things (leaf color vs leaf presence). For MODIS phenology I recommend Mark Friedl’s product. At large scales, Landsat is hard (see work by Eli Melass). We’re also currently working on using GOES to model/forecast phenology, which has MUCH higher temporal resolution than MODIS but similar spatial, but the timeseries is < 2 yr so far

**Comment by jenniferholm** [comment]
@rgknox - I like Mike's suggestions of Phenocam and eventually GOES, those seem really good for benchmarking. 

This paper isn't necessarily benchmarking global phenology, but it does a nice analysis of the environmental **drivers** correlating to global green-up (I think you're "leaf-on") and brown-down (I think you're "leaf-off"). They review 188 papers and look at these drivers: latitude, temperature, precipitation, continent, and plant functional type (PFT) to predict phenology.
So this could be nice to use during the analysis phase of your phenology additions, to see if your phenology patterns are ballpark and correctly attributed to the 'right' environmental explanations/drivers. 

https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.02443

**Comment by rosiealice** [comment]
I asked Kyla Dahlin about this from a semi-arid phenology perspective, and she said:

"I think I do have access to the repo but I haven't been keeping track of anything CLM/FATES/etc recently... I haven't looked at the VIPPHEN stuff (link in the thread linked to below) but it looks really cool - at least it looks like they considered multiple growing seasons per year, which is important in eastern Africa. Phenocams are cool but they are waaaaaay biased toward the US (they make fluxnet look like a reasonable set of global samples) so from a lower latitude/southern hemisphere perspective they're pretty unhelpful.

And I agree that landsat is tough for global scale stuff - not because it's so much data volume, but the temporal resolution (16 days) means there are huge cloud cover gaps. At some point in the future there will probably be some nice Sentinel-2 + Landsat products that help address this, but then they'll only go as far back as the Sentinel-2 record, which is like 2015 for A and 2017 for B."

**Comment by rgknox** [comment]
closing due to lots of time elapsed,  feel free to comment and we will open this back up
