### ISSUE TITLE
Plant hydraulics failure calculating rhizosphere shells

### ISSUE THREAD

**Issue by pollybuotte** [NGEET/fates#504]
I have a single point case with one active PFT, created with this script
[create_fates_single_pt.txt](https://github.com/NGEET/fates/files/2972379/create_fates_single_pt.txt)
This case ran for 100 years with plant hydraulics off.  With hydraulics on it fails with this error in the cesm.log:

![image](https://user-images.githubusercontent.com/30528250/54453463-fa916600-471c-11e9-9173-7d69af307d28.png)

From line 5182 in PlantHydraulicsMod it appears the problem may be zero area in the rhizosphere shells:
![image](https://user-images.githubusercontent.com/30528250/54453627-52c86800-471d-11e9-914c-f576bfd21036.png)

Can anyone suggest reasonable values for the absorbing root radius (currently 0.0001) or specific root length (currently 25) that may cure the problem?  Or if the source of the error is elsewhere?  Thanks.

**Comment by xuchongang** [comment]
@pollybuotte,  would you please let me know which year does this happen? I think this should not be related to radium and specific root length.

**Comment by pollybuotte** [comment]
@xuchongang, this happens the first year of the simulation.  In this case that was 1979.

**Comment by JunyanDing** [comment]
I got this error message too. I think the cause of this is there is no plants left at that time. The area in the code is the area of forest cover.  In my case, this error either occur in the first year or about 20 yr after.

**Comment by ckoven** [comment]
@JunyanDing the area being passed here: https://github.com/NGEET/fates/blob/master/biogeophys/FatesPlantHydraulicsMod.F90#L1643
isn't the canopy area, its the nominal FATES site area (which is a constant = 1 ha), so this shouldn't be the issue here.  Perhaps the root length is becoming a tiny negative number and thus its getting a complex answer in https://github.com/NGEET/fates/blob/master/biogeophys/FatesPlantHydraulicsMod.F90#L5182? 

In any case, sounds like a thing that needs to be done is to go through and add some conditionals, setting root uptake and or perhaps a high level conditional to set overall plant hydraulic dynamics as zero when the plant coverage gets to be very small?

**Comment by pollybuotte** [comment]
@JunyanDing I ran a case with prescribed, static stand structure.  It successfully made it through the first year, past the July 13 failure date.  I'm now running for 50 years.  Maybe this will help us track down the problem.

**Comment by pollybuotte** [comment]
These figures show water content across root shells.  It appears the lack of ordering from inner to outer by water content and instances of 0 water are problems.
![image](https://user-images.githubusercontent.com/30528250/61899974-5924e700-af3c-11e9-94fe-189008c27c94.png)

@bchristo suggested looking into FillDrainRhizShells.  A brief look indicates there may be a problem when dwat_kg=0 and shells do not get ordered according to water content starting on line 2098.

**Comment by rgknox** [comment]
this seems pretty old and we have changed the hydro code significantly since this post, @pollybuotte feel free to re-open if this issue is still relevant
