### ISSUE TITLE
Patch dynamics after landscape disturbance

### ISSUE THREAD

**Issue by pollybuotte** [NGEET/fates#569]
Several of us have been talking about how patches are formed after fire, or any other landscape-level disturbance like logging or insect outbreaks.  The goal is to have the surviving trees populate the new patch, rather than creating a new patch from bare ground based on the area of the disturbance.  For example, we want to allow the possibility for a ground fire to remove the understory and not affect the taller trees.  The surviving trees then populate the newly created patch, which is the size of the fire.  This will allow the real world conditions where fire maintains a forest of shade intolerant, fire resistant trees. Or where selective logging reduces stand density.  Starting this issue to get feedback from the larger group.

**Comment by rosiealice** [comment]
Hi Polly... Can you be a bit more specific about what you need to happen? I
think that, in principle, a fire should make a 'new' patch, but that patch
should be populated by the things that survived the fire. Have you been
finding that that doesn't actually happen in 'real' simulations?

**Comment by rosiealice** [comment]
Is part of the thing you want to happen to do with the fates_mortality_disturbance_fraction parameter? 

As in, a fire comes through, thins out the understorey and also kills some canopy trees, but we don't necessarily want the area under the killed canopy trees to go into the 'new patch' area, because you want to retain the average canopy properties of the burned area.  I feel like making the fates_mortality_disturbance_fraction at the 'PPA-like' end of the spectrum (i.e. near zero, right @ckoven?) when there is a fire would facilitate that?

Apart from that, as Ryan illustrated (thanks!) we -should- already be able to burn out the under-storey and not have that make any new patches because that only happens if we kill canopy trees by definition...
