### ISSUE TITLE
specific root length unit error

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#607]
This is only relevant to the hydraulics model.

In the parameter file, specific root length has has the units m g-1.  Which is what you do typically see from the field measurements.
https://github.com/NGEET/fates/blob/master/parameter_files/fates_params_default.cdl#L230

Here is where it is being used to calculate the length.  But notice that the calculations here think the parameter is in units of [m kg-1].  The resulting calculation gives you a length in [m], where the srl is multiplied by mass (fnrt_c) * c2b which is units [kg].

https://github.com/NGEET/fates/blob/master/biogeophys/FatesPlantHydraulicsMod.F90#L747

I'm working on refactors which address this unit error, but I want others to be aware of this issue in the mean time.  You can either just add the conversion factor into the code, or change you parameter file value to one that is m/kg, thereby multiplying the value by 1000.

The default value we have in the parameter file (25 m/g) does seem consistent with a quick scan of the literature, in that SRL values seem to be around 5-30+ [m/g].  So, alternatively, for the time being, some may consider just changing the value in the code to 25000*.

*I have not done sensitivity on changing this value.

**Comment by jenniferholm** [comment]
@rgknox - thanks for posting this. It's funny that we talked about this same unit error today. In my branch I made the one line change to convert the m/g to m/kg. It seems better to add the unit conversion in the code, since like you said most of the field measurements are recorded in m/g. So the units and values of fates_hydr_srl in the parameter file will still make sense to (measurement) people. 

I have a pull request basically ready to go. Do you want me to submit that, but it's also a super easy one line fix that can be included in your refactor. 
The HydraulicsMod in fact already has the unit conversion "g_per_kg" constant, so it's all set up. 

https://github.com/NGEET/fates/blob/fbbcafd02986f42cf62992c1b99497d026da69fd/biogeophys/FatesPlantHydraulicsMod.F90#L41

**Comment by rgknox** [comment]
That's great @jenniferholm , thanks
