### ISSUE TITLE
New parameters for next parameter file update

### ISSUE THREAD

**Issue by JessicaNeedham** [NGEET/fates#616]
I have a new parameter that needs to go into the next update to the parameter file. 
This parameter is a switch that will turn cohort age tracking on (1) or off (0). 

https://github.com/JessicaNeedham/fates/blob/dd28a9b10476e56126976bc6a8074ec88bd7aa06/parameter_files/fates_params_default.cdl#L532-L534

https://github.com/JessicaNeedham/fates/blob/dd28a9b10476e56126976bc6a8074ec88bd7aa06/parameter_files/fates_params_default.cdl#L1232

The only other change is that the default number of cohort age bin edges needs to be 2 and not 1. When age tracking is off, cohorts will be assigned age 0 and it will not be incremented. But they still need to go into the first(only) age bin to stop crashes.

https://github.com/JessicaNeedham/fates/blob/dd28a9b10476e56126976bc6a8074ec88bd7aa06/parameter_files/fates_params_default.cdl#L683

Other parameters associated with cohort age tracking and size- and age-dependent mortality are already in the default parameter file.

**Comment by rgknox** [comment]
Thanks @JessicaNeedham , folks if we can come up with other parameters we want to add along with this one, feel free to describe them here

**Comment by jenniferholm** [comment]
Cool! Here is a list of additional parameters that are needed in FatesPlantRespPhotosynthMod so that the availability and competition for nutrients has an affect on photosynthesis. 

These parameters should go into the parameter file ==
'fates_leaf_flnr' = fraction of leaf N in Rubisco by PFT.
These are used in the Walker et al. 2014 equations for N and P limitation on photosynthesis ("vcmax~np relationship coefficient") ==
vcmax_np1,  vcmax_np2, vcmax_np3, vcmax_np4 which vary by PFT.


https://github.com/jenniferholm/fates-1/commit/aba747c3915bbb1455b00574f05014b6a423f013

In my first go around I labeled these are starting with "fates_prt_" but then realized they should be labeled "fates_eca_" to match Ryan's naming convention. 

Global parameters that I hard coded in FatesPlantRespPhotosynthMod ==
jmax_np1, jmax_np2, jmax_np3 
! vcmax25 parameters from Bonan et al (2011) JGR, 116, doi:10.1029/2010JG001593
      fnr = 7.16_r8
      act25 = 3.6_r8 !umol/mgRubisco/min

**Comment by alistairrogers** [comment]
Hi Jennifer, 

There are some errors in the parameters for the equation first presented by Thornton & Zimmerman (2007). I discuss these in more detail in Rogers (2014) but in brief

1. FNR is not 7.16. This estimate does not include the presence of peptide bonds. The real number is 6.22 g Rubisco g-1 N in Rubisco. Using 7.12 underestimates the N cost of Rubisco and will result in an overestimation of photosynthesis.

2. Act25 was originally 60 in Peter's paper (overestimate). My calculation suggests this should be 47 µmol CO2 g-1 Rubisco s-1. This is based on the assumption that Rubisco is fully activated (known unknown but safe assumption), has a kcat of 3.4 s-1 (known unknown but best guess for a C3) and an molecular mass of 575kDa (know know). 

These corrections are not trival. The difference between Pete'rs original numbers and my corrections resulted in a -37 Gt CO2 y-1 difference in GPP (CLM4.5). It may be a wash with your numbers but better to get them right.

Cheers
Alistair

**Comment by jenniferholm** [comment]
@alistairrogers - thanks so much for spotting these errors in FNR and Act25. Especially because as you state, they are not trival! Thanks. I admit I was just using previous values that have been used in ELM and I needed to do a further, and more recent, literature check. Thanks for reminding me about your paper. Could I cite it (as a comment) in the photosynthesis submodule  of the code? It's always nice to remind future users where latest values come from.

**Comment by alistairrogers** [comment]
Sure

**Comment by rgknox** [comment]
Per discussions with @xuchongang and @bchristo, fates_hydro_resid_node
will get a name and unit change.   Here is the current entry:
https://github.com/NGEET/fates/blob/master/parameter_files/fates_params_default.cdl#L221

The parameter sets the residual water content for different plant compartments, and the units currently are in relative water content, synonomous with fraction of saturation.

The change will make the units in volumetric water content, with the same units as fates_hydro_thetas_node.

https://github.com/NGEET/fates/blob/master/parameter_files/fates_params_default.cdl#L233

The name will also be changed to: fates_hydro_thetar_node, making it more similar to fates_hydro_thetas_node

**Comment by serbinsh** [comment]
As per the FATES modeling call discussion today (2020-04-16) @Qianyuxuan has an in-progress PR for adding Medlyn.  As discussed and since this is a "minor" change that allows for different representations of the same process (stomatal conductance) she will be updating the parameter file with a new stomatal_model (switch name TBD) switch (e.g. 1 - BallBerry, 2-Medlyn) as well as two new PFT vectors for g1 (stomatal slope)

fates_leaf_stomatal_slope_ballberry
fates_leaf_stomatal_slope_medlyn (or maybe better yet fates_leaf_stomatal_slope_uso)

but we will have just one vector for g0 allowing for PFT specific g0 but where the same g0 is used for either as we agreed these should be the same since its a measurable quantity and represents the min gs

As such it would be good if we could get this param file changes in as well

**Comment by ckoven** [comment]
should we pull out the fire threshold parameter into the parameter file?  currently its hard coded (here: https://github.com/NGEET/fates/blob/master/main/EDTypesMod.F90#L150) but it seems like an important uncertainty term to be able to vary.  @jkshuman do you think pulling it out of the fortran makes sense?

**Comment by jkshuman** [comment]
@ckoven yes. I agree it should go into the param file. good idea to include it with this issue.

**Comment by rgknox** [comment]
Per issue #290:

Remove existing root profile parameters, and consolidate to one parameter set and one mode switch for each PFT.  (@JunyanDing , do you have any thoughts or new rooting parametes you foresee us needing in the future?)
 
```
     real(r8), allocatable :: fnrt_prof_mode(:)       ! Fine root profile functional form
     real(r8), allocatable :: fnrt_prof_a(:)              ! Fine root profile scaling parameter A
     real(r8), allocatable :: fnrt_prof_b(:)              ! Fine root profile scaling parameter B
```

**Comment by ckoven** [comment]
Another thing to add for this is `fates_logging_dbhmax` for the logging code that @aldivi and I are collaborating on, which will allow things like forest thinning for fire purposes, etc.  this came up in #491.

**Comment by rgknox** [comment]
Started working on a branch to address this group of parameter changes:  https://github.com/rgknox/fates/tree/paramfile_updates

Started by adding changes needed for: #608  

Make a note in this thread if you have any updates:
@ckoven @JessicaNeedham @jenniferholm @jkshuman @rosiealice

**Comment by rgknox** [comment]
@JessicaNeedham , can you confirm that the parameters in your first post are not needed anymore, now that we have the namelist flag: hlm_use_cohort_age_tracking ?

**Comment by JessicaNeedham** [comment]
Hi @rgknox - correct - the parameter in the first post is no longer needed. Thanks

**Comment by rgknox** [comment]
@jenniferholm , Regarding the vcmax_np  parameters, those are from the Walker model, not the ECA model right?  Also, should we consider allowing these to be dimensioned by leaf age (along with PFT)?
@walkeranthonyp @alistairrogers

**Comment by rgknox** [comment]
@ckoven , could you provide the exact metadata you would like to see on the fates_logging_dbhmax parameter (dimensions, long name, unit)?

**Comment by ckoven** [comment]
@rgknox  @aldivi
```
	double fates_logging_dbhmax ;
		fates_logging_dbhmax:units = "cm" ;
		fates_logging_dbhmac:long_name = "Maximum dbh below which logging is applied" ;
```
With a default value of some large number like 1e5, so that it is not used by default?

**Comment by jkshuman** [comment]
@rgknox @ckoven 

double fates_fire_threshold ;
		fates_fire_threshold:units = "kW/m" ;
		fates_fire_threshold:long_name = "spitfire parameter, fire intensity energy threshold for tracking fires that spread" ;

default value of 50.0
no changes to in-code parameter name (only used in SFMainMod)

**Comment by jenniferholm** [comment]
@rgknox - The vcmax_np1, vcmax_np2, vcmax_np3, vcmax_np4 parameters are from Walker et al. 2014, and used in the ECA code, and vary by PFT. 
 Each one has the same descriptor of: "vcmax~np relationship coefficient") ==

Here are the values I found from an ELM parameter file, but I'm not sure if these are the up-to-date values. Here is the parameter file name: clm_params.c170414_defNUP_isvc_defmort_arctichvcmax_defNFIX_defPHTASE.nc

double vcmax_np1(pft) ;
		vcmax_np1:long_name = "vcmax~np relationship coefficient" ;
		vcmax_np1:unit = "" ;
	double vcmax_np2(pft) ;
		vcmax_np2:long_name = "vcmax~np relationship coefficient" ;
		vcmax_np2:unit = "" ;
	double vcmax_np3(pft) ;
		vcmax_np3:long_name = "vcmax~np relationship coefficient" ;
		vcmax_np3:unit = "" ;
	double vcmax_np4(pft) ;
		vcmax_np4:long_name = "vcmax~np relationship coefficient" ;
		vcmax_np4:unit = "" ;

vcmax_np1 = 3.934375, 4.18625, 2.2828125, 4.8, 4.02421875, 3.878125, 4.8, 
    4.7175, 3.9421875, 3.7, 3.7859375, 3.73046875, 4.0046875, 3.7859375, 
    4.43859375, 3.7859375, 3.7390625, 3.7390625, 3.7390625, 3.7390625, 
    3.7390625, 3.7390625, 3.7390625, 3.7390625, 3.7390625 ;

 vcmax_np2 = 0.65625, 0.7125, 0.853125, 0.7453125, 0.7640625, 0.9140625, 
    0.8015625, 0.91875, 1.096875, 0.6, 1.134375, 0.8390625, 0.646875, 
    1.134375, 0.6703125, 1.134375, 0.740625, 0.740625, 0.740625, 0.740625, 
    0.740625, 0.740625, 0.740625, 0.740625, 0.740625 ;

 vcmax_np3 = 0.175, 0.09, 0.0775, 0.08625, 0.07125, 0.19125, 0.12125, 0.185, 
    0.1225, 0.04, 0.1725, 0.17125, 0.0825, 0.1725, 0.14625, 0.1725, 0.1675, 
    0.1675, 0.1675, 0.1675, 0.1675, 0.1675, 0.1675, 0.1675, 0.1675 ;

 vcmax_np4 = 0.282, 0.282, 0.282, 0.282, 0.282, 0.282, 0.282, 0.282, 0.282, 
    0.282, 0.282, 0.282, 0.282, 0.282, 0.282, 0.282, 0.282, 0.282, 0.282, 
    0.282, 0.282, 0.282, 0.282, 0.282, 0.282 ;
