### ISSUE TITLE
Phenology and restarting

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#627]
So, in trying to make a run using a restart files from a previous run (and turning spitfire on, a'la @jkshuman 's discovery that we can't just run fire from the beginning), I discovered that all of the cold deciduous trees had died in the new run (is that a 'branch' run? I've never been very au fait with that terminology). 

Anyway, I think the issue is that we are recording as our 'state' variable for the phenology counters the absolute date of the leafon and leafoff events. As in, after 30 years, the 
fates_drought_leafoffdate and fates_leafoffdate variables have values in the 10'000s... 

When we restart the run from the beginning, the model recalculates 'timesinceleafoff' and 'timesinceleafon' from model_day_int and the restart leafoffdate and leafondate variables read in from the restart. That means that we get huge negative values for timesinceleafoff and timesinceleafon
https://github.com/NGEET/fates/blob/3b6ac22180b0cc873005a141d7967c4fa9fd6b45/biogeochem/EDPhysiologyMod.F90#L701

Which of course then breaks all of the conditional statements that use them and the phenology routines go haywire. 

I'm not sure if there is a solution to this that doesn't require a re-write of this part of the phenology code. Putting this here for sanity checking.

**Comment by rgknox** [comment]
@rosiealice , so if I understand correctly, when you do restart that is not a "continue_run", or one that uses finitdat to restart, then the model_day_int does not continue from the previous run... Yeah, i can see how this would be a problem...  Perhaps the solution then is to change cleafondat, cleafoffdat, dleafondate and dleafoffdate to be DOY instead of absolute day?
I changed this logic around, I liked the absolutes in terms of making the trigger logic simpler, but I did not foresee this complication.  Sorry for this @rosiealice

**Comment by adrifoster** [comment]
I don't think this would impact this problem but I think I brought this up at a recent-ish meeting - do you think having an extra status of "new cohort" so we wouldn't have to do workarounds for not having any cleafondate/offdate from the previous simulation years. This would be for all cohorts started from bare ground and then any that get established?

**Comment by rgknox** [comment]
@adrifoster , so this would be a cohort-level flag that specifies if the cohort is so new that it has not reached its first phenological event?

**Comment by adrifoster** [comment]
Yeah - though maybe this wouldn't matter much. We could also have a "bare ground" site status.

**Comment by rgknox** [comment]
now I remember one of the reasons I wanted absolute dates... At least one of our triggers was longer than a year.  For instance, if we had not had a cold day in 400 days, then we would trigger a leaf off status, one that is "never cold".  However, doing this with a Day Of Year based tracking system is more difficult (because 400>365).

**Comment by rgknox** [comment]
I suppose a simple solution would be to add our own model day offset in the FATES portion of the restart file.  On cold-starts the model day offset would be 0, and on restarts it gets read in.  model_day_int would include the FATES offset.

**Comment by rosiealice** [comment]
Thanks all. I don't know that at the moment we need a new cohort flag given that the phenology triggers are all at the site level (or maybe I'm missing an application of that I haven't thought of). If we moved to a more disaggregated phenology at the PFT level etc. we might need to think about that. 

I think an internal FATES model day would indeed work @rgknox.  We could call it 'FATES_PHNEOLOGY_DAY' or something to avoid confusion with the HLM day counter? Then it would just need be consistent with the cleafoff etc. values.

**Comment by jkshuman** [comment]
@rosiealice give the results that Leah Birch (WHRC) presented at the CLM meeting on improved arctic/boreal phenology triggers maybe we should talk about PFT level. Implementing her changes would involve disaggregating to the PFT level. thoughts?

the interim solution from you and @rgknox of a FATE_PHENOLOGY_DAY sounds good
