### ISSUE TITLE
SEED_GERM_ELEM history variable is basically zeros

### ISSUE THREAD

**Issue by ckoven** [NGEET/fates#715]
I just noticed that the history variable SEED_GERM_ELEM, which is the total element flux (so mass of C,N, etc per area per time) of seed transforming into new recruits, is basically all zeros.  looking through the code, I think its because of how we're handling the litter%seed_germ here: https://github.com/NGEET/fates/blob/master/biogeochem/EDPhysiologyMod.F90#L1830-L1832 where we zero the flux prior to it arriving in the history diagnostics (here: https://github.com/NGEET/fates/blob/master/main/FatesHistoryInterfaceMod.F90#L3144-L3145 ).  not a super big deal, but f we want to track the mass of recruitment fluxes, we may need to rework slightly in order to send the right thing to history.

**Comment by glemieux** [comment]
It looks like the calculation on https://github.com/NGEET/fates/blob/master/main/FatesHistoryInterfaceMod.F90#L4075 is incorrect.  The meta data on the output is incorrect is wrong too.

**Comment by rgknox** [comment]
After reviewing this a little bit.  litter%seed_germ is indeed a pool, not a flux.  Although, in our current implementation, all of the germinated seed should be converted to new recruit whenever we call recruitement. Since that is called every day, I'm not surprised that the pool is zero when we call history.  So, why do we have the pool then?  We have it to give us future flexibility on when we want to call recruitment.  Also, when nutrients are enabled, its possible that one of the elements C, N or P will be in excess from the seed rain, and less used by the recruits. In this case, that element will have some residual in the seed_germ pool following recruitment. 
The unit fixes that @glemieux indicates above are also correct as I understand it.
