### ISSUE TITLE
Update FATES respiration model

### ISSUE THREAD

**Issue by ckoven** [NGEET/fates#729]
Hi All-
in various threads and discussions, the topic of the (autotrophic) respiration model in FATES has come up a bunch recently.  right now there are a few distinct issues:
1. sapwood respiration scaling continues to have problems related to sapwood allometry (e.g. #392); Xinyuan Wei is looking into this right now so I won't get into it further here.
2. we'd like to include respiration acclimation, as in CLM5 and other models, following Atkin 2008 model or one of its descendants.
3. Possibly we should move away from using a Q10 model for short-term respiration responses to temperature to something more data-constrained.
4. FATES currently uses a relatively low default value of the growth respiration parameter (0.11 as here: https://github.com/NGEET/fates/blob/master/parameter_files/fates_params_default.cdl#L862-L863), the value of that was lowered during the CLM4->CLM5 development pathway (from a prior value of 0.3 in CLM4, according to the CLM4 tech note) when the Atkins respiration model was added, but in FATES we hadn't done the second part.  This may be a reason why FATES's NPP tends to be on the high side in initial uncalibrated runs (and possibly LAI as well because of leaf optimization logic).

I'd like to propose that, for 2-4 above, we add an option to include other respiration forms besides the current one based on Ryan et al 1991.  In doing a cursory scan through the literature, it seems like the potential top candidate is this model from an Atkin 2017 book chapter (https://link.springer.com/chapter/10.1007%2F978-3-319-68703-2_6), which combines the long-term acclimation model that CLM5 and others use, with a short-term temperature sensitivity model based on Heskel et al 2016 (https://doi.org/10.1073/pnas.1520282113).  I think this is also the formulation that JULES is now using (https://www.nature.com/articles/s41467-017-01774-z).  It is however different from the acclimating respiration model in CLM5, which still uses a Q10 for the short-term temperature sensitivity, per @danicalombardozzi's paper https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2015GL065934

A few questions though: 
1. Are there other respiration models that we should be considering using as well?
2. All the above applies to leaves only, should we continue to use the existing scheme for sapwood and fine roots (as CLM5 does)?
3. Is anyone else working on this at present?  If not, I was thinking of trying to put in a basic representation of this so that we can start to play around with it in our global calibration efforts.

**Comment by danicalombardozzi** [comment]
Updating to using the Heskel et al. 2016 temperature sensitivity sounds great! My paper was prior to the Heskel work, so didn't incorporate it.

In response to your questions:
1) I don't know of any, but I haven't been tracking this literature closely
2) Most of the data are available for leaves, not fine roots or sapwood. If I remember correctly, I found that leaf respiration acclimation vs whole-plant respiration acclimation led to relatively large differences in total C. The assumptions are a) sapwood and roots acclimate the same as leaves; or b) fine roots and sapwood don't acclimate. I'm not sure which is "better", but it may be worth testing the response of including only leave acclimation and adding sapwood and fine root acclimation to identify the difference. 
3) I don't know of anyone actively working on it.

**Comment by alistairrogers** [comment]
I took a look at the Atkin Chapter (a comprehensive resource for modelers). It seems the Heskel equation in combination with the Atkin equation see (Fig 6.7) would appear to offer an improved representation in FATES. The Heskel et al 2016 equation is independent of PFT and requires an estimate of ambient leaf temperature to scale Rd25. The Rd25 comes from the Atkin et al 2015 equation and is linked to leaf N content but requires three parameters and an estimate of Tgrowth (over ten days). Some thoughts.

1. The r1 parameter (identical for all PFTs) determines the rate of Rd from Na which is added to r0 (the basal rate at 0oC - PFT specific) r2 (identical for all PFTs) is multiplied by Tgrowth. The PFT specific parameter r0 exerts considerable influence - a 50%   increase in Rd from the lowest to the highest PFT estimate but I'm struggling to see how R0 is derived. It would be good to get to bottom of this.

2. I think we want to make sure we use the same integration period for acclimation of Tgrowth for photosynthesis and respiration.

3. It would be informative to see how the Rd25 derived from Atkin varies as a function of the Vcmax prescribed in FATES with the kummarathunge temperature acclimation. i.e. is there a strong case for independent temperature acclimation of Rd and Vcmax and could we use a Vcmax based estimate of Rd25 instead of relying on the r0,1 and 2 parameters.

4. If we include temperature acclimation of Rd25 following Atkin we should also include temperature acclimation of Vcmax and Jmax (underway Claire & Cherry). Obviously it would not be good to have Rd acclimate but not gross photosynthesis.

4. Given the influence of the PFT specific r0 parameter it may be worth revisiting the GlobResp data base to derive R0 values for the FATES PFTs. This might also identify holes in data coverage. I'm assuming we've got good Na data constraints for the FATES PFTs.

[Atkin2017_Chapter_LeafRespirationInTerrestrialBi.pdf](https://github.com/NGEET/fates/files/6286419/Atkin2017_Chapter_LeafRespirationInTerrestrialBi.pdf)
[Heskel et al 2016.pdf](https://github.com/NGEET/fates/files/6286856/Heskel.et.al.2016.pdf)
[Atkin et al 2015.pdf](https://github.com/NGEET/fates/files/6286859/Atkin.et.al.2015.pdf)

**Comment by rgknox** [comment]
@mpaiao notes that we are currently using some hard-coded parameter for leaf maintenance respiration, see here:

https://github.com/NGEET/fates/pull/800/files?diff=unified&w=1#diff-f62a39ba3dc682263ce52ac5f1bec68ac12bc849e5987c1a793938bb2a1339e8R505-R506

Or source code from sci.1.55.2_api.22.0.0:  https://github.com/NGEET/fates/blob/sci.1.55.2_api.22.0.0/biogeophys/FatesPlantRespPhotosynthMod.F90#L503

**Comment by ckoven** [comment]
Just wanted to note that I have a branch now that includes the Atkin et al 2017 respiration model as discussed above in this issue.  Currently in early testing.

https://github.com/NGEET/fates/compare/master...ckoven:fates:respiration_newmodels#diff-91857484d2b9a65d2cb5a44ecfc1614fbc9567fede7867365cdc42502faa13f0
