### ISSUE TITLE
Allow "inventory" initialization from height as well as diameter

### ISSUE THREAD

**Issue by adrifoster** [NGEET/fates#826]
To facilitate initialization from LiDAR/CHM or other height data, it would be beneficial to allow initialization using cohort heights rather than diameters. One could calculate diameter from height before feeding the file into the model, but this would require updating initialization files any time the height allometry parameters or equations changed.

I think it should be relatively straightforward to calculate diameter from input height and then proceed with the initialization logic as it is now.

I am working on this!

**Comment by adrifoster** [comment]
We already read in height in the current patch init file, but don't do anything with it.

If folks have design ideas for how to specify to use dbh vs. height, I would welcome them! (@rgknox, @glemieux)

Some ideas....

1.  If DBH is 0.0, try to read height, and vice versa. We would just use the existing file and subroutine and add a check. This is probably the easiest but has the potential for lots of user error. 
2. Similar to above but specify in the control file if we want dbh or height. I kind of like this better. 
3. Completely separate function and file? Not sure if this is really necessary. You'd probably still need to specify in the control file if it is a height or dbh initialization.

**Comment by jkshuman** [comment]
Sounds great @adrifoster tagging @mpaiao for thoughts on this as well.

**Comment by ckoven** [comment]
Hi @adrifoster this would be great.  Since we are already allowing 0.0 values in for height and treating those as missing data, I'd suggest we stick with that convention and do the same thing for diameter.  Probably there should be a check that either all plants have a nonzero diameter or all plants have a nonzero height, and then use whichever of those is valid?

**Comment by ckoven** [comment]
Also what should the model do if it is using a capped diameter:height allometry and the measured height is greater than the cap?  Throw an error or use the diameter of the height cap?

**Comment by adrifoster** [comment]
> Also what should the model do if it is using a capped diameter:height allometry and the measured height is greater than the cap? Throw an error or use the diameter of the height cap?

This is a very good point... Perhaps throw an error? The init step occurs right away so you wouldn't get too far. 

The message would likely be to either change the initialization data or update the dbh_maxheight value? 

Otherwise we could warn the user and then just use the diameter of the height cap as you say.

**Comment by JoshuaRady** [comment]
I thought about implementing this at one point because I have young sites with a lot of trees right around breast height.  I ended up just using the next year's data since I had it, when the trees were taller.

I like the approach of looking for DBH first and using height if it is not available or is 0.  If you really want the model to initialize from height only you could omit the DBH values.

I would suggest that it is better to use the max height for capped allometries.  Since the allometries in FATES represent mean behaviors their height caps seem best interpreted as asymptotes for the mean height.  (At least that is how I have thought about it.)  If so it then it follows that heights above the cap will be common for real world trees, and we shouldn't exclude them.  A warning could be written to the log.

**Comment by rgknox** [comment]
Not sure if you are at this step yet, but we can control the type of input format in the first argument of the control file:
https://github.com/NGEET/fates/wiki/Model-Initialization-Modes#Guide_for_a_Cold_Start_Simulation_with_Inventory_Case_3

I suppose this would be type 2

**Comment by glemieux** [comment]
Closing per https://github.com/NGEET/fates/pull/1104
