### ISSUE TITLE
Grass PFT'

### ISSUE THREAD

**Issue by ZacharyRobbins** [NGEET/fates#884]
Currently grass PFT's have the same assignment as all cohorts with regards to allocation of coarse woody debris (and thus fuels). This ultimately results in grass producing 1000 hour fuels, 100 hour fuels and other nonsense. Ultimately the best fix for this would be to make CWD assignment a PFT parameter so each PFT can assign to different pools based on the fuel it would produce. However in the short term my fix has been to say if PFT is not woody then all the normal CWD pools go to the dead leaves pool.  This works in the case of grass, however, would not work with grass, chaparral and a tree PFT. Below I illustrate the fuel output for a grass PFT, as you can see it creates trunk fuels (based on fuel classification) which don't map well with how spitfire works. 
![image](https://user-images.githubusercontent.com/25291127/181098119-da875e4a-ca13-4633-b809-9e5d8ad4bab1.png)
@ckoven

**Comment by ckoven** [comment]
Thanks @ZacharyRobbins for identifying this!

**Comment by rgknox** [comment]
@ZacharyRobbins could you point to the location in the code where you see grasses contributing to CWD please?

**Comment by ckoven** [comment]
@rgknox I think the issue is here: https://github.com/NGEET/fates/blob/master/biogeochem/EDPhysiologyMod.F90#L2248-L2272. The sapwood gets routed to CWD pools when it turns over, whether it is from woody or nonwoody plants.  Since grasses can still have "sapwood" (i.e. live stem biomass) in their allometry, that biomass get sent to the CWD pools.  And since FATES uses the same partitioning to fuel classes for all PFTs / plant sizes, that is generating small but nonzero amounts of coarse fuel.

**Comment by jkshuman** [comment]
Agreed. Thank you for identifying this @ZacharyRobbins and a fix for the problem!

**Comment by glemieux** [comment]
Closed per #891
