### ISSUE TITLE
tveg causing errors in global nocomp runs

### ISSUE THREAD

**Issue by JessicaNeedham** [NGEET/fates#973]
The variable tveg is causing errors in global runs with nocomp on. With debug=TRUE  there's a floating divide by zero error here: 

https://github.com/NGEET/fates/blob/e663a6e66851c65c476e82785ad679a42545f9e1/main/FatesHistoryInterfaceMod.F90#L4311

from site_area_veg being zero in some patches - defined here: 

https://github.com/NGEET/fates/blob/e663a6e66851c65c476e82785ad679a42545f9e1/main/FatesHistoryInterfaceMod.F90#L4277

If debug is false then the following error gets triggered:

Non blocking write for variable (FATES_TVEG, varid=260) failed (Number of subarray requests/regions=1, Size of data local to this process = 792). NetCDF: Numeric conversion not representable (err=-60).

**Comment by glemieux** [comment]
Thanks for the heads up @JessicaNeedham.  I think this suggests that somehow there are patches on a bareground site that aren't having their `patchno` set to zero.

**Comment by glemieux** [comment]
@JessicaNeedham how quickly into the run are you seeing this?   In the cases you are running are you using a restart?

**Comment by JessicaNeedham** [comment]
@glemieux divide by zero error occurs during compilation if debug=TRUE. Otherwise, if debug=FALSE, the error occurs after the first history file is written to output. I get one month of output and then it crashes. 

My simulations are from bare ground.

**Comment by glemieux** [comment]
@JessicaNeedham determined that the issue is due to the fact that the `patchno` is only being set with a `hlm_use_spmode` check instead of a broader nocomp check here:
https://github.com/NGEET/fates/blob/e663a6e66851c65c476e82785ad679a42545f9e1/biogeochem/EDPatchDynamicsMod.F90#L1285-L1293

Updating allows an fbg+nocomp case with debug on to run successfully.  That said, when I tried replicating the fix on Cori, I was coming up with new error that I'm still trying to track down.

**Comment by glemieux** [comment]
I was able to replicate this issue with clm-fates on Cheyenne as well when running a test in debug mode.  Testing out the fix via https://github.com/NGEET/fates/pull/976, however, resulted in a downstream issue in spitfire with `patchno` again, so this will need some more review.  I suspect we simply need to add in the common `nocomp_pft_label` check on the patch loops in SFMainMod.
